name: Avocatier
description: Le Blog
meta_description: "Blog Avocatier"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.avocatier.com'
google_analytics: 'UA-50624100-5'

# Details for the RSS feed generator
url:            'http://blog.avocatier.com/'
author:         'Avocatier'
